### ISSUE TITLE
"No Trick Rainbow Rings" code doesn't add RainbowRing score

### ISSUE THREAD

**Issue by RFunk195** [HyperBE32/ScoreGenerations#1]
This also applies to mods where tricks from rainbow rings are disabled such as the Unleashed adventure packs. I assume they're identified differently from normal rainbow rings which could be why the mod doesn't recognize them. If this could be fixed, it would make many mods with these type of rainbow rings more compatible with Score.

**Comment by hyperbx** [comment]
That code redirects rainbow ring behaviour to dash rings - you still receive score if you change it for the latter. I don't think there's a way for me to detect that, unfortunately. I'll see what I can do either way.

**Comment by hyperbx** [comment]
Fixed in commit https://github.com/HyperBE32/ScoreGenerations/commit/c717dc04e98eea43e49fd1be5afb07c8631b23a4 - will be part of the next update when it releases.
