### ISSUE TITLE
Score system

### ISSUE THREAD

**Issue by Paulnou** [HyperBE32/ScoreGenerations#2]
This mod is what i was looking for, create your own score system is one of the best idea i've ever seen. We can make the S rank a little bit more difficult for each stage we want and that's pretty cool.
Unfortunatly, i found a tiny issue in my playthrough...  The required points to have an S rank in Sonic Generations were normally 50 000 points, depending on the time and the rings. And broo, it's way too easy. So i decided to make the ranking system as close as possible as Sonic Unleashed has, which is a bit harsh, but really rewarding and enjoyable if you manage to get an S rank. So that's mean the only way to get points through the stage is to kill enemies, and doing tricks and nothing else. (no points when destroying objects, no points when getting rings ect...) And i tried to make the time/ring/speed bonus algorithm in the stage result the most balanced as possible. But with this mod for some strange reason, the points required to have an S rank is different for each level. It's sometimes 55 000 points, 70 000 points or 80 000 points, etc... to have an S rank, and it's pretty hard, or even impossible in my opinion to make the ranking system the most balanced as possible to each level of the game/pack level mods (Unleashed project) if the score required changes in every level, it's sometimes way to easy to have an S rank with my ranking system (Cool Edge), but it's sometimes literally impossible for no reason (Dragoon road, Speed Highway), but it's perfectly balanced for Windmill Isle act 1 (with the same harshness Sonic Unleashed has, that means if you don't touch the checkpoint, you can't have an S rank). So what i'm asking for, is to be able to set the required points to each level as we want without going through coding, because i really have no idea how this works.
And again, thank you for this mod. I'm not sure if this comment will be useful, but i hope that it will be read by someone who worked on this mod.
Have a nice day

**Comment by hyperbx** [comment]
You only really need to use Lua if you're doing anything specific with any of the totals, but the rank requirements are already defined in `ScoreGenerations.ini` - see the base mod's INI and scroll to the bottom and you'll see each stage ID represented with a hash prefix (e.g. `#ghz200`) with their respective rank requirements.

**Comment by Paulnou** [comment]
Thank you so much, i didn't do the lua thing, but going into the folder
.INI helped me a lot.

Le mer. 23 févr. 2022 à 23:37, Gabriel S. ***@***.***> a
écrit :
