### ISSUE TITLE
Crash in Score Generations v1.4

### ISSUE THREAD

**Issue by Kaplan3527** [HyperBE32/ScoreGenerations#3]
The game crashes when I enable "restore last checkpoint score".
(Score Generations v1.4)

**Comment by hyperbx** [comment]
Thanks for reporting, I've fixed the crashing, but I've noticed your score resets entirely at checkpoints now - looking into it.

**Comment by hyperbx** [comment]
Fixed in commits https://github.com/HyperBE32/App-Extension-Mods/commit/43b750dc5c4f31ddad04f9ff850ff49f4482650c and https://github.com/HyperBE32/App-Extension-Mods/commit/553689d50333306d718835b699f438be182666de.
