### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by Paulnou** [HyperBE32/ScoreGenerations#4]
Hello,
When I beat a boss after playing any stage even without finishing it, the game crashes when the results screen appears. I want to clarify that the game does not crash if I beat a boss without having played a stage before. 
Also, I modified the ScoreGenerations.ini file a bit so that I could customize the points required to have an S rank in each stage and in several stage packs before the update (unleashed project, 06 project and more), so I created multiple ScoreGenerations.ini files for each respective stage pack. And maybe it had something with the new update and makes the results screen crash the game when i beat a boss after playing a level. But it was working fine before the update. 
Thank you and have a nice day

**Comment by hyperbx** [comment]
Thanks for reporting - this was a weird one for sure, and proved to be very tedious to debug.

This should be fixed as of commits https://github.com/HyperBE32/App-Extension-Mods/commit/84317fd745cad36f53c43db364edcc1007aecb5f and https://github.com/HyperBE32/App-Extension-Mods/commit/832f85595d2f2087bbe743ae20175f05e93abaec - will release a hotfix later today.

**Comment by Paulnou** [comment]
Great! No problem.
