### ISSUE TITLE
Time bonus algorithm

### ISSUE THREAD

**Issue by Paulnou** [HyperBE32/ScoreGenerations#5]
Thank you for the update,
But i encountered a new issue. It's not a huge problem, but it was working fine before the update.
The time bous algorithm is not working like before. you can no longer add points or subtract them to a specific score. For example, I was using this algorithm: 140000 - (seconds * 400). And every second, the player lost 400 points, which forced him to reach the big golden ring as quickly as possible. (although it could reach negative score if it took too long) but it was a strict way to calculate the score like sonic unleashed did, but it doesn't work anymore. Thank you and have a nice day

**Comment by hyperbx** [comment]
Thanks for reporting - I did think something was a bit off about the final score, turns out the elapsed time is returning zero now. Looking into it.

**Comment by hyperbx** [comment]
Fixed in commit https://github.com/HyperBE32/App-Extension-Mods/commit/4dd50e19671858fb7b9db0ead70c0bf5632b8767.
