### ISSUE TITLE
E rank

### ISSUE THREAD

**Issue by Paulnou** [HyperBE32/ScoreGenerations#6]
Hi

I don't know if it's an issue, but the update says that it added the E rank. But when I get this rank in a stage, there's the right music and the right Sonic's voice reaction (when he says "NoOoOooOoo...!", for instance) But it's the D rank animation, and the E rank doesn't show up. It's just a weird brown scare. Did I forget to enable something ? Please let me know and have a nice day.

**Comment by hyperbx** [comment]
Score Generations only officially supports ranks used by Sonic Generations - there is no intention to make E ranks and S ranks supported natively, as they do not fit in the UI for the results screen. These additional ranks are meant to be accessed using the API for mods that have the facilities to display them correctly, such as HUD mods.
