### ISSUE TITLE
 integrity check failed-click ok to vist the legitimate source for this mod

### ISSUE THREAD

**Issue by WEASELMOB** [HyperBE32/ScoreGenerations#7]
this keeps appearing after I click "save and play'' i put the Unleashed Project: The Complete Addon mods into HMM but when i put score gen this keeps popping up. can you help me?

**Comment by hyperbx** [comment]
This might be an issue with the new HE1ML that's currently used in the Development channel for Hedge Mod Manager, I'm yet to make fixes for it.
