### ISSUE TITLE
small image text for DiscordFrontiers

### ISSUE THREAD

**Issue by hazzaclark** [HyperBE32/ScoreGenerations#8]
Just a minor nitpick however, when using the Character Swapper code in HedgeModManager, the Small Image Text doesn't change based on which character you are playing as 

Super Sonic

![image](https://github.com/HyperBE32/App-Extension-Mods/assets/107435091/4a5574bb-34a3-43fd-8d09-4c3ead8ef9ed)

Knuckles

![image](https://github.com/HyperBE32/App-Extension-Mods/assets/107435091/3ac875f7-9915-477c-9013-77d8c9792dbd)

Amy

![image](https://github.com/HyperBE32/App-Extension-Mods/assets/107435091/fa39515c-a257-4b10-8d9a-27ac42c0b03d)

Tails

![image](https://github.com/HyperBE32/App-Extension-Mods/assets/107435091/fbfd5e29-5195-4f24-afe9-a93e8bd7aa54)

**Comment by hyperbx** [comment]
Interesting, during testing that tooltip would never show up for me, so maybe that's an issue with 80% zoom on Discord. I'll look into it, thanks.

**Comment by hyperbx** [comment]
This actually seems to be an issue with a dangling pointer, so I'll mark this as a bug.

**Comment by hyperbx** [comment]
Fixed in commit https://github.com/HyperBE32/App-Extension-Mods/commit/96998550053349cc80c18b8df3032d928fe051eb.
